In [45]:
#import dependencies
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM, Dense, InputLayer, Dropout, BatchNormalization
from keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score
from keras.regularizers import l2

# Problem Introduction
Predict outcomes of NBA games

In [46]:
#create df of preprocessed data - game data from 2004-2024
df = pd.read_csv('nbaDatabasePreProcessed2004-2024-allPost.csv')
df

,date,homeTeam,homeTeam_id,homeTeam_win%,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,...,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season,isPlayoffGame
0,2024-06-17,Boston Celtics,BOS,0.792079,80,21,106,28,39,19,...,28,35,18,4,4,13,20,Boston Celtics,2023-2024,True
1,2024-06-14,Dallas Mavericks,DAL,0.611650,63,40,122,34,27,31,...,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024,True
2,2024-06-12,Dallas Mavericks,DAL,0.607843,62,40,99,31,20,19,...,30,36,26,4,6,9,19,Boston Celtics,2023-2024,True
3,2024-06-09,Boston Celtics,BOS,0.795918,78,20,105,25,29,29,...,34,43,21,5,3,15,17,Boston Celtics,2023-2024,True
4,2024-06-06,Boston Celtics,BOS,0.793814,77,20,107,37,26,23,...,33,43,9,8,1,11,16,Boston Celtics,2023-2024,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,0.000000,0,1,104,21,19,27,...,36,47,24,9,5,13,28,Indiana Pacers,2004-2005,False
25727,2004-11-03,Boston Celtics,BOS,0.000000,0,1,95,22,31,30,...,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005,False
25728,2004-11-02,Los Angeles Lakers,LAL,1.000000,1,0,89,24,26,22,...,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005,False
25729,2004-11-02,Detroit Pistons,DET,1.000000,1,0,87,19,18,22,...,27,36,8,4,5,16,24,Detroit Pistons,2004-2005,False
25730,2004-11-02,Dallas Mavericks,DAL,1.000000,1,0,107,30,24,25,...,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005,False

In [47]:
#maps franchises to subjectID
subjectID_dict = {
    "ATL": 1,
    "BOS": 2,
    "BKN": 3,
    "CHA": 4,
    "CHI": 5,
    "CLE": 6,
    "DAL": 7,
    "DEN": 8,
    "DET": 9,
    "GSW": 10,
    "HOU": 11,
    "IND": 12,
    "LAC": 13,
    "LAL": 14,
    "MEM": 15,
    "MIA": 16,
    "MIL": 17,
    "MIN": 18,
    "NOP": 19,
    "NYK": 20,
    "OKC": 21,
    "ORL": 22,
    "PHI": 23,
    "PHX": 24,
    "POR": 25,
    "SAC": 26,
    "SAS": 27,
    "TOR": 28,
    "UTA": 29,
    "WAS": 30,
    "NOH": 19, #New Orleans Hornets is same franchise as NOP- New Orleans Pelicans
    "NJN": 3, #New Jersey Nets relocated to Brooklyn
    "SEA": 21, #Seattle Supersonics Relocated to OKC
    "NOK": 19, #New Orleans Hornets relocated to OKC 2005-2007 - Eventually became New Orleans Pelicans
    
}

In [48]:
#map the subject IDs to a number to handle franchise moves
df["homeTeamSubject_id"] = df["homeTeam_id"].map(subjectID_dict)
df["awayTeamSubject_id"] = df["awayTeam_id"].map(subjectID_dict)

cols = df.columns.tolist()
cols.insert(cols.index("homeTeam_id") + 1, cols.pop(cols.index("homeTeamSubject_id")))
cols.insert(cols.index("awayTeam_id") + 1, cols.pop(cols.index("awayTeamSubject_id")))
df = df[cols]

df

,date,homeTeam,homeTeam_id,homeTeamSubject_id,homeTeam_win%,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,...,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season,isPlayoffGame
0,2024-06-17,Boston Celtics,BOS,2,0.792079,80,21,106,28,39,...,28,35,18,4,4,13,20,Boston Celtics,2023-2024,True
1,2024-06-14,Dallas Mavericks,DAL,7,0.611650,63,40,122,34,27,...,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024,True
2,2024-06-12,Dallas Mavericks,DAL,7,0.607843,62,40,99,31,20,...,30,36,26,4,6,9,19,Boston Celtics,2023-2024,True
3,2024-06-09,Boston Celtics,BOS,2,0.795918,78,20,105,25,29,...,34,43,21,5,3,15,17,Boston Celtics,2023-2024,True
4,2024-06-06,Boston Celtics,BOS,2,0.793814,77,20,107,37,26,...,33,43,9,8,1,11,16,Boston Celtics,2023-2024,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,6,0.000000,0,1,104,21,19,...,36,47,24,9,5,13,28,Indiana Pacers,2004-2005,False
25727,2004-11-03,Boston Celtics,BOS,2,0.000000,0,1,95,22,31,...,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005,False
25728,2004-11-02,Los Angeles Lakers,LAL,14,1.000000,1,0,89,24,26,...,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005,False
25729,2004-11-02,Detroit Pistons,DET,9,1.000000,1,0,87,19,18,...,27,36,8,4,5,16,24,Detroit Pistons,2004-2005,False
25730,2004-11-02,Dallas Mavericks,DAL,7,1.000000,1,0,107,30,24,...,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005,False

In [49]:
#generate a binary winner column
df['winner_binary'] = (df['winner'] == df['awayTeam']).astype(int)
df

C:\Users\Max Braithwaite\AppData\Local\Temp\ipykernel_12388\767967889.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['winner_binary'] = (df['winner'] == df['awayTeam']).astype(int)

,date,homeTeam,homeTeam_id,homeTeamSubject_id,homeTeam_win%,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,...,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season,isPlayoffGame,winner_binary
0,2024-06-17,Boston Celtics,BOS,2,0.792079,80,21,106,28,39,...,35,18,4,4,13,20,Boston Celtics,2023-2024,True,0
1,2024-06-14,Dallas Mavericks,DAL,7,0.611650,63,40,122,34,27,...,31,18,2,5,13,19,Dallas Mavericks,2023-2024,True,0
2,2024-06-12,Dallas Mavericks,DAL,7,0.607843,62,40,99,31,20,...,36,26,4,6,9,19,Boston Celtics,2023-2024,True,1
3,2024-06-09,Boston Celtics,BOS,2,0.795918,78,20,105,25,29,...,43,21,5,3,15,17,Boston Celtics,2023-2024,True,0
4,2024-06-06,Boston Celtics,BOS,2,0.793814,77,20,107,37,26,...,43,9,8,1,11,16,Boston Celtics,2023-2024,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,6,0.000000,0,1,104,21,19,...,47,24,9,5,13,28,Indiana Pacers,2004-2005,False,1
25727,2004-11-03,Boston Celtics,BOS,2,0.000000,0,1,95,22,31,...,41,20,9,2,16,26,Philadelphia 76ers,2004-2005,False,1
25728,2004-11-02,Los Angeles Lakers,LAL,14,1.000000,1,0,89,24,26,...,48,17,10,8,16,21,Los Angeles Lakers,2004-2005,False,0
25729,2004-11-02,Detroit Pistons,DET,9,1.000000,1,0,87,19,18,...,36,8,4,5,16,24,Detroit Pistons,2004-2005,False,0
25730,2004-11-02,Dallas Mavericks,DAL,7,1.000000,1,0,107,30,24,...,43,21,9,6,15,19,Dallas Mavericks,2004-2005,False,0

In [50]:
#populate dfIDtoStat - should be double the size of df
homedf = df[['date', 'homeTeamSubject_id', 'homeTeam_wins', 'homeTeam_losses']]
homedf.columns = ['date', 'team_id', 'team_wins', 'team_losses']
awaydf = df[['date', 'awayTeamSubject_id', 'awayTeam_wins', 'awayTeam_losses']]
awaydf.columns = ['date', 'team_id', 'team_wins', 'team_losses']

dfIDtoStat = pd.concat([homedf, awaydf], ignore_index=True)
dfIDtoStat

             date  team_id  team_wins  team_losses
0      2024-06-17        2         80           21
1      2024-06-14        7         63           40
2      2024-06-12        7         62           40
3      2024-06-09        2         78           20
4      2024-06-06        2         77           20
...           ...      ...        ...          ...
51457  2004-11-03       12          1            0
51458  2004-11-03       23          1            0
51459  2004-11-02        8          0            1
51460  2004-11-02       11          0            1
51461  2004-11-02       26          0            1

[51462 rows x 4 columns]

In [ ]:
#showcase of the first iteration
window_size =1
exX =[]
exY = []
for index, row in df.iterrows():
        homeTeam_id = row['homeTeamSubject_id']
        awayTeam_id = row['awayTeamSubject_id']
        date = row['date']
        #limit dfWindow to include rows that occured before date of row we are on
        dfWindow_before_date = dfIDtoStat[dfIDtoStat['date']< date]
        homeTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].shape[0]
        awayTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].shape[0]
        if homeTeam_occurrences > window_size and awayTeam_occurrences > window_size:
                homeTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].sort_values(by='date', ascending=False).head(window_size))
                awayTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].sort_values(by='date', ascending=False).head(window_size))
                print(date)
                print(homeTeam_window)
                print(awayTeam_window)
                print(type(homeTeam_window))
                homeTeam_window = homeTeam_window.drop(columns=['date', 'team_id'])
                awayTeam_window = awayTeam_window.drop(columns=['date', 'team_id'])
                homeTeam_window = homeTeam_window.to_numpy()
                awayTeam_window = awayTeam_window.to_numpy()
                combined_window = np.hstack((homeTeam_window, awayTeam_window))
                exX.append(combined_window)
                exY.append(row['winner_binary'])
                print(exX)
                print(exY)
                break

2024-06-17
             date  team_id  team_wins  team_losses
25732  2024-06-14        2         79           21
25733  2024-06-12        2         79           20
         date  team_id  team_wins  team_losses
1  2024-06-14        7         63           40
2  2024-06-12        7         62           40
<class 'pandas.core.frame.DataFrame'>
[array([[79, 21, 63, 40],
       [79, 20, 62, 40]], dtype=int64)]
[0]

In [ ]:
#showcase of the first iteration
window_size =2
exX =[]
exY = []
for index, row in df.iterrows():
        homeTeam_id = row['homeTeamSubject_id']
        awayTeam_id = row['awayTeamSubject_id']
        date = row['date']
        #limit dfWindow to include rows that occured before date of row we are on
        dfWindow_before_date = dfIDtoStat[dfIDtoStat['date']< date]
        homeTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].shape[0]
        awayTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].shape[0]
        if homeTeam_occurrences > window_size and awayTeam_occurrences > window_size:
                homeTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].sort_values(by='date', ascending=False).head(window_size))
                awayTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].sort_values(by='date', ascending=False).head(window_size))
                print(date)
                print(homeTeam_window)
                print(awayTeam_window)
                print(type(homeTeam_window))
                homeTeam_window = homeTeam_window.drop(columns=['date', 'team_id'])
                awayTeam_window = awayTeam_window.drop(columns=['date', 'team_id'])
                homeTeam_window = homeTeam_window.to_numpy()
                awayTeam_window = awayTeam_window.to_numpy()
                combined_window = np.hstack((homeTeam_window, awayTeam_window))
                exX.append(combined_window)
                exY.append(row['winner_binary'])
                print(exX)
                print(exY)
                break

In [54]:
#generate the X Y matrices
def df_to_X_y(df, dfWindow, window_size):
    X = []
    y = []
    #each team must have played window_size games before data can be extracted
    for index, row in df.iterrows():
        homeTeam_id = row['homeTeamSubject_id']
        awayTeam_id = row['awayTeamSubject_id']
        date = row['date']
        #limit dfWindow to include rows that occured before date of row we are on
        dfWindow_before_date = dfWindow[dfWindow['date']< date]
        homeTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].shape[0]
        awayTeam_occurrences = dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].shape[0]
        if homeTeam_occurrences > window_size and awayTeam_occurrences > window_size:
            homeTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == homeTeam_id].sort_values(by='date', ascending=False).head(window_size).drop(columns=['date', 'team_id']))
            awayTeam_window = (dfWindow_before_date[dfWindow_before_date['team_id'] == awayTeam_id].sort_values(by='date', ascending=False).head(window_size).drop(columns=['date', 'team_id']))
            homeTeam_window = homeTeam_window.to_numpy()
            awayTeam_window = awayTeam_window.to_numpy()
            combined_window = np.hstack((homeTeam_window, awayTeam_window))
            X.append(combined_window)
            y.append(row['winner_binary'])
    
    return np.array(X), np.array(y)

In [55]:
#X1.Shape is num data, window size, variables
X, y = df_to_X_y(df, dfIDtoStat, 1)
X.squeeze(axis=1)
X.shape, y.shape

((25698, 1, 4), (25698,))

In [61]:
X = X.squeeze(axis=1)
X.shape

(25698, 4)

In [62]:
#80-10-10 split
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)
X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((20558, 4), (20558,), (2570, 4), (2570,), (2570, 4), (2570,))

In [63]:
model = Sequential()
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [64]:
#early stopping if model does not improve performance for 50 epochs
earlystopping = EarlyStopping(monitor='val_loss', patience=50, restore_best_weights=True)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [65]:
#simple model fit
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=100, callbacks=[earlystopping])

Epoch 1/100
643/643 [==============================] - 1s 1ms/step - loss: 0.7728 - accuracy: 0.6232 - val_loss: 0.6375 - val_accuracy: 0.6432
Epoch 2/100
643/643 [==============================] - 1s 901us/step - loss: 0.6346 - accuracy: 0.6438 - val_loss: 0.6561 - val_accuracy: 0.6292
Epoch 3/100
643/643 [==============================] - 1s 894us/step - loss: 0.6333 - accuracy: 0.6424 - val_loss: 0.6287 - val_accuracy: 0.6475
Epoch 4/100
643/643 [==============================] - 1s 901us/step - loss: 0.6302 - accuracy: 0.6438 - val_loss: 0.6267 - val_accuracy: 0.6553
Epoch 5/100
643/643 [==============================] - 1s 897us/step - loss: 0.6288 - accuracy: 0.6459 - val_loss: 0.6281 - val_accuracy: 0.6572
Epoch 6/100
643/643 [==============================] - 1s 893us/step - loss: 0.6287 - accuracy: 0.6432 - val_loss: 0.6471 - val_accuracy: 0.6335
Epoch 7/100
643/643 [==============================] - 1s 952us/step - loss: 0.6294 - accuracy: 0.6426 - val_loss: 0.6273 - val_accuracy: 0.6498
Epoch 8/100
643/643 [==============================] - 1s 896us/step - loss: 0.6277 - accuracy: 0.6439 - val_loss: 0.6282 - val_accuracy: 0.6475
Epoch 9/100
643/643 [==============================] - 1s 888us/step - loss: 0.6283 - accuracy: 0.6439 - val_loss: 0.6259 - val_accuracy: 0.6599
Epoch 10/100
643/643 [==============================] - 1s 904us/step - loss: 0.6273 - accuracy: 0.6448 - val_loss: 0.6523 - val_accuracy: 0.6261
Epoch 11/100
643/643 [==============================] - 1s 901us/step - loss: 0.6271 - accuracy: 0.6457 - val_loss: 0.6253 - val_accuracy: 0.6580
Epoch 12/100
643/643 [==============================] - 1s 901us/step - loss: 0.6263 - accuracy: 0.6468 - val_loss: 0.6327 - val_accuracy: 0.6420
Epoch 13/100
643/643 [==============================] - 1s 904us/step - loss: 0.6264 - accuracy: 0.6452 - val_loss: 0.6260 - val_accuracy: 0.6518
Epoch 14/100
643/643 [==============================] - 1s 899us/step - loss: 0.6247 - accuracy: 0.6495 - val_loss: 0.6251 - val_accuracy: 0.6638
Epoch 15/100
643/643 [==============================] - 1s 896us/step - loss: 0.6255 - accuracy: 0.6473 - val_loss: 0.6403 - val_accuracy: 0.6342
Epoch 16/100
643/643 [==============================] - 1s 913us/step - loss: 0.6251 - accuracy: 0.6479 - val_loss: 0.6231 - val_accuracy: 0.6630
Epoch 17/100
643/643 [==============================] - 1s 897us/step - loss: 0.6246 - accuracy: 0.6462 - val_loss: 0.6235 - val_accuracy: 0.6588
Epoch 18/100
643/643 [==============================] - 1s 897us/step - loss: 0.6249 - accuracy: 0.6482 - val_loss: 0.6265 - val_accuracy: 0.6525
Epoch 19/100
643/643 [==============================] - 1s 893us/step - loss: 0.6234 - accuracy: 0.6499 - val_loss: 0.6241 - val_accuracy: 0.6615
Epoch 20/100
643/643 [==============================] - 1s 893us/step - loss: 0.6238 - accuracy: 0.6494 - val_loss: 0.6257 - val_accuracy: 0.6553
Epoch 21/100
643/643 [==============================] - 1s 897us/step - loss: 0.6232 - accuracy: 0.6511 - val_loss: 0.6246 - val_accuracy: 0.6595
Epoch 22/100
643/643 [==============================] - 1s 952us/step - loss: 0.6235 - accuracy: 0.6499 - val_loss: 0.6229 - val_accuracy: 0.6623
Epoch 23/100
643/643 [==============================] - 1s 902us/step - loss: 0.6230 - accuracy: 0.6515 - val_loss: 0.6231 - val_accuracy: 0.6615
Epoch 24/100
643/643 [==============================] - 1s 899us/step - loss: 0.6229 - accuracy: 0.6513 - val_loss: 0.6246 - val_accuracy: 0.6572
Epoch 25/100
643/643 [==============================] - 1s 910us/step - loss: 0.6230 - accuracy: 0.6510 - val_loss: 0.6234 - val_accuracy: 0.6595
Epoch 26/100
643/643 [==============================] - 1s 899us/step - loss: 0.6232 - accuracy: 0.6487 - val_loss: 0.6236 - val_accuracy: 0.6615
Epoch 27/100
643/643 [==============================] - 1s 910us/step - loss: 0.6223 - accuracy: 0.6507 - val_loss: 0.6243 - val_accuracy: 0.6638
Epoch 28/100
643/643 [==============================] - 1s 904us/step - loss: 0.6227 - accuracy: 0.6514 - val_loss: 0.6239 - val_accuracy: 0.6591
Epoch 29/100
643/643 [==============================] - 1s 913us/step - loss: 0.6223 - accuracy: 0.6512 - val_loss: 0.6252 - val_accuracy: 0.6599
Epoch 30/100
643/643 [==============================] - 1s 921us/step - loss: 0.6224 - accuracy: 0.6519 - val_loss: 0.6229 - val_accuracy: 0.6681
Epoch 31/100
643/643 [==============================] - 1s 908us/step - loss: 0.6221 - accuracy: 0.6519 - val_loss: 0.6218 - val_accuracy: 0.6615
Epoch 32/100
643/643 [==============================] - 1s 919us/step - loss: 0.6218 - accuracy: 0.6514 - val_loss: 0.6216 - val_accuracy: 0.6638
Epoch 33/100
643/643 [==============================] - 1s 907us/step - loss: 0.6218 - accuracy: 0.6523 - val_loss: 0.6234 - val_accuracy: 0.6595
Epoch 34/100
643/643 [==============================] - 1s 908us/step - loss: 0.6217 - accuracy: 0.6527 - val_loss: 0.6216 - val_accuracy: 0.6595
Epoch 35/100
643/643 [==============================] - 1s 918us/step - loss: 0.6217 - accuracy: 0.6509 - val_loss: 0.6230 - val_accuracy: 0.6549
Epoch 36/100
643/643 [==============================] - 1s 946us/step - loss: 0.6216 - accuracy: 0.6524 - val_loss: 0.6210 - val_accuracy: 0.6661
Epoch 37/100
643/643 [==============================] - 1s 901us/step - loss: 0.6212 - accuracy: 0.6521 - val_loss: 0.6227 - val_accuracy: 0.6545
Epoch 38/100
643/643 [==============================] - 1s 918us/step - loss: 0.6210 - accuracy: 0.6544 - val_loss: 0.6249 - val_accuracy: 0.6549
Epoch 39/100
643/643 [==============================] - 1s 913us/step - loss: 0.6205 - accuracy: 0.6533 - val_loss: 0.6217 - val_accuracy: 0.6599
Epoch 40/100
643/643 [==============================] - 1s 915us/step - loss: 0.6210 - accuracy: 0.6514 - val_loss: 0.6223 - val_accuracy: 0.6677
Epoch 41/100
643/643 [==============================] - 1s 911us/step - loss: 0.6208 - accuracy: 0.6521 - val_loss: 0.6209 - val_accuracy: 0.6630
Epoch 42/100
643/643 [==============================] - 1s 919us/step - loss: 0.6207 - accuracy: 0.6516 - val_loss: 0.6211 - val_accuracy: 0.6599
Epoch 43/100
643/643 [==============================] - 1s 921us/step - loss: 0.6203 - accuracy: 0.6539 - val_loss: 0.6200 - val_accuracy: 0.6615
Epoch 44/100
643/643 [==============================] - 1s 911us/step - loss: 0.6205 - accuracy: 0.6524 - val_loss: 0.6244 - val_accuracy: 0.6556
Epoch 45/100
643/643 [==============================] - 1s 910us/step - loss: 0.6205 - accuracy: 0.6532 - val_loss: 0.6203 - val_accuracy: 0.6654
Epoch 46/100
643/643 [==============================] - 1s 927us/step - loss: 0.6201 - accuracy: 0.6534 - val_loss: 0.6220 - val_accuracy: 0.6665
Epoch 47/100
643/643 [==============================] - 1s 938us/step - loss: 0.6199 - accuracy: 0.6523 - val_loss: 0.6200 - val_accuracy: 0.6638
Epoch 48/100
643/643 [==============================] - 1s 941us/step - loss: 0.6199 - accuracy: 0.6526 - val_loss: 0.6206 - val_accuracy: 0.6619
Epoch 49/100
643/643 [==============================] - 1s 930us/step - loss: 0.6203 - accuracy: 0.6528 - val_loss: 0.6205 - val_accuracy: 0.6654
Epoch 50/100
643/643 [==============================] - 1s 915us/step - loss: 0.6199 - accuracy: 0.6528 - val_loss: 0.6221 - val_accuracy: 0.6541
Epoch 51/100
643/643 [==============================] - 1s 908us/step - loss: 0.6199 - accuracy: 0.6538 - val_loss: 0.6243 - val_accuracy: 0.6502
Epoch 52/100
643/643 [==============================] - 1s 924us/step - loss: 0.6198 - accuracy: 0.6533 - val_loss: 0.6204 - val_accuracy: 0.6619
Epoch 53/100
643/643 [==============================] - 1s 921us/step - loss: 0.6198 - accuracy: 0.6559 - val_loss: 0.6203 - val_accuracy: 0.6638
Epoch 54/100
643/643 [==============================] - 1s 916us/step - loss: 0.6198 - accuracy: 0.6520 - val_loss: 0.6204 - val_accuracy: 0.6626
Epoch 55/100
643/643 [==============================] - 1s 916us/step - loss: 0.6198 - accuracy: 0.6535 - val_loss: 0.6214 - val_accuracy: 0.6630
Epoch 56/100
643/643 [==============================] - 1s 922us/step - loss: 0.6197 - accuracy: 0.6540 - val_loss: 0.6199 - val_accuracy: 0.6642
Epoch 57/100
643/643 [==============================] - 1s 905us/step - loss: 0.6197 - accuracy: 0.6533 - val_loss: 0.6198 - val_accuracy: 0.6661
Epoch 58/100
643/643 [==============================] - 1s 911us/step - loss: 0.6197 - accuracy: 0.6539 - val_loss: 0.6200 - val_accuracy: 0.6611
Epoch 59/100
643/643 [==============================] - 1s 933us/step - loss: 0.6195 - accuracy: 0.6526 - val_loss: 0.6214 - val_accuracy: 0.6591
Epoch 60/100
643/643 [==============================] - 1s 910us/step - loss: 0.6199 - accuracy: 0.6542 - val_loss: 0.6202 - val_accuracy: 0.6615
Epoch 61/100
643/643 [==============================] - 1s 929us/step - loss: 0.6196 - accuracy: 0.6532 - val_loss: 0.6203 - val_accuracy: 0.6626
Epoch 62/100
643/643 [==============================] - 1s 918us/step - loss: 0.6195 - accuracy: 0.6543 - val_loss: 0.6198 - val_accuracy: 0.6607
Epoch 63/100
643/643 [==============================] - 1s 910us/step - loss: 0.6195 - accuracy: 0.6523 - val_loss: 0.6212 - val_accuracy: 0.6654
Epoch 64/100
643/643 [==============================] - 1s 922us/step - loss: 0.6199 - accuracy: 0.6553 - val_loss: 0.6193 - val_accuracy: 0.6630
Epoch 65/100
643/643 [==============================] - 1s 911us/step - loss: 0.6193 - accuracy: 0.6541 - val_loss: 0.6195 - val_accuracy: 0.6603
Epoch 66/100
643/643 [==============================] - 1s 910us/step - loss: 0.6194 - accuracy: 0.6536 - val_loss: 0.6212 - val_accuracy: 0.6603
Epoch 67/100
643/643 [==============================] - 1s 911us/step - loss: 0.6196 - accuracy: 0.6531 - val_loss: 0.6189 - val_accuracy: 0.6626
Epoch 68/100
643/643 [==============================] - 1s 904us/step - loss: 0.6193 - accuracy: 0.6539 - val_loss: 0.6220 - val_accuracy: 0.6576
Epoch 69/100
643/643 [==============================] - 1s 905us/step - loss: 0.6194 - accuracy: 0.6530 - val_loss: 0.6196 - val_accuracy: 0.6650
Epoch 70/100
643/643 [==============================] - 1s 916us/step - loss: 0.6193 - accuracy: 0.6526 - val_loss: 0.6220 - val_accuracy: 0.6642
Epoch 71/100
643/643 [==============================] - 1s 930us/step - loss: 0.6197 - accuracy: 0.6538 - val_loss: 0.6204 - val_accuracy: 0.6646
Epoch 72/100
643/643 [==============================] - 1s 908us/step - loss: 0.6195 - accuracy: 0.6549 - val_loss: 0.6219 - val_accuracy: 0.6607
Epoch 73/100
643/643 [==============================] - 1s 930us/step - loss: 0.6193 - accuracy: 0.6541 - val_loss: 0.6193 - val_accuracy: 0.6658
Epoch 74/100
643/643 [==============================] - 1s 922us/step - loss: 0.6191 - accuracy: 0.6539 - val_loss: 0.6190 - val_accuracy: 0.6642
Epoch 75/100
643/643 [==============================] - 1s 921us/step - loss: 0.6192 - accuracy: 0.6551 - val_loss: 0.6192 - val_accuracy: 0.6615
Epoch 76/100
643/643 [==============================] - 1s 911us/step - loss: 0.6190 - accuracy: 0.6552 - val_loss: 0.6203 - val_accuracy: 0.6615
Epoch 77/100
643/643 [==============================] - 1s 911us/step - loss: 0.6191 - accuracy: 0.6547 - val_loss: 0.6185 - val_accuracy: 0.6634
Epoch 78/100
643/643 [==============================] - 1s 902us/step - loss: 0.6191 - accuracy: 0.6538 - val_loss: 0.6191 - val_accuracy: 0.6646
Epoch 79/100
643/643 [==============================] - 1s 902us/step - loss: 0.6194 - accuracy: 0.6552 - val_loss: 0.6191 - val_accuracy: 0.6607
Epoch 80/100
643/643 [==============================] - 1s 901us/step - loss: 0.6194 - accuracy: 0.6538 - val_loss: 0.6187 - val_accuracy: 0.6630
Epoch 81/100
643/643 [==============================] - 1s 899us/step - loss: 0.6192 - accuracy: 0.6558 - val_loss: 0.6198 - val_accuracy: 0.6607
Epoch 82/100
643/643 [==============================] - 1s 904us/step - loss: 0.6189 - accuracy: 0.6542 - val_loss: 0.6191 - val_accuracy: 0.6646
Epoch 83/100
643/643 [==============================] - 1s 915us/step - loss: 0.6190 - accuracy: 0.6523 - val_loss: 0.6200 - val_accuracy: 0.6642
Epoch 84/100
643/643 [==============================] - 1s 927us/step - loss: 0.6192 - accuracy: 0.6535 - val_loss: 0.6196 - val_accuracy: 0.6591
Epoch 85/100
643/643 [==============================] - 1s 907us/step - loss: 0.6190 - accuracy: 0.6535 - val_loss: 0.6191 - val_accuracy: 0.6603
Epoch 86/100
643/643 [==============================] - 1s 918us/step - loss: 0.6187 - accuracy: 0.6562 - val_loss: 0.6191 - val_accuracy: 0.6611
Epoch 87/100
643/643 [==============================] - 1s 927us/step - loss: 0.6189 - accuracy: 0.6542 - val_loss: 0.6212 - val_accuracy: 0.6549
Epoch 88/100
643/643 [==============================] - 1s 977us/step - loss: 0.6190 - accuracy: 0.6541 - val_loss: 0.6191 - val_accuracy: 0.6607
Epoch 89/100
643/643 [==============================] - 1s 929us/step - loss: 0.6192 - accuracy: 0.6536 - val_loss: 0.6201 - val_accuracy: 0.6634
Epoch 90/100
643/643 [==============================] - 1s 918us/step - loss: 0.6188 - accuracy: 0.6542 - val_loss: 0.6201 - val_accuracy: 0.6595
Epoch 91/100
643/643 [==============================] - 1s 922us/step - loss: 0.6189 - accuracy: 0.6550 - val_loss: 0.6208 - val_accuracy: 0.6599
Epoch 92/100
643/643 [==============================] - 1s 923us/step - loss: 0.6189 - accuracy: 0.6532 - val_loss: 0.6206 - val_accuracy: 0.6658
Epoch 93/100
643/643 [==============================] - 1s 982us/step - loss: 0.6186 - accuracy: 0.6537 - val_loss: 0.6188 - val_accuracy: 0.6654
Epoch 94/100
643/643 [==============================] - 1s 947us/step - loss: 0.6190 - accuracy: 0.6534 - val_loss: 0.6215 - val_accuracy: 0.6568
Epoch 95/100
643/643 [==============================] - 1s 896us/step - loss: 0.6191 - accuracy: 0.6539 - val_loss: 0.6187 - val_accuracy: 0.6654
Epoch 96/100
643/643 [==============================] - 1s 904us/step - loss: 0.6189 - accuracy: 0.6541 - val_loss: 0.6195 - val_accuracy: 0.6658
Epoch 97/100
643/643 [==============================] - 1s 912us/step - loss: 0.6189 - accuracy: 0.6538 - val_loss: 0.6188 - val_accuracy: 0.6630
Epoch 98/100
643/643 [==============================] - 1s 927us/step - loss: 0.6188 - accuracy: 0.6560 - val_loss: 0.6196 - val_accuracy: 0.6603
Epoch 99/100
643/643 [==============================] - 1s 918us/step - loss: 0.6187 - accuracy: 0.6552 - val_loss: 0.6217 - val_accuracy: 0.6619
Epoch 100/100
643/643 [==============================] - 1s 953us/step - loss: 0.6183 - accuracy: 0.6539 - val_loss: 0.6189 - val_accuracy: 0.6634

In [66]:
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
print(accuracy_score(y_test, y_pred_binary))

81/81 [==============================] - 0s 613us/step
0.6622568093385214